### PR TITLE
added 2 detect methods

### PR DESCRIPTION
**Pull request by Marchuck**
Hi, I've added these methods to your wrapper. Should it help :)

### CODE REVIEW

**Comment by DavidPacioianu** [comment]
Have you tested it? It would be nice to add a toBinary method to FileUtils, that converts a bitmap into bytes array.

**Comment by Marchuck** [comment]
Yes, but when bitmap is not properly rotated, face cannot be detected, so I got empty response in callback. I found solution for this problem: we can rotate selected bitmap recursively up to 4 times (dealing with bad-rotated bitmaps with faces), to avoid this issue:
`onSuccess(FaceAnalysis[] response)`
`...`
`if (retry < 4 && (response == null || response.length == 0 )) {`
`retry++;`
`Matrix matrix = new Matrix();`
`matrix.postRotate(90);`
`bmp = Bitmap.createBitmap(bmp, 0, 0, bmp.getWidth(), bmp.getHeight(), matrix, true);`
//retry here with new bitmap
}

**Comment by DavidPacioianu** [comment]
I don't think it is necessary, because, in some cases, it would increase the time required to analyse the photo too much.

**Comment by Marchuck** [comment]
Anyway, the Bitmap->byte[] converter works correctly and code is ready to merge.

**Comment by DavidPacioianu** [comment]
You forgot to import android.graphics.Bitmap and java.io.ByteArrayOutputStream

**Pull request merged**
